plugins {
    id 'java'
    id 'application'
    id 'com.gradleup.shadow' version '9.5.1'
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

repositories {
    mavenCentral()
}

application {
    mainClass.set("Launcher")
}

dependencies {
    String javaFxVersion = '25.0.4'
    ['win', 'mac', 'mac-aarch64', 'linux', 'linux-aarch64'].each { platform ->
        implementation "org.openjfx:javafx-base:${javaFxVersion}:${platform}"
        implementation "org.openjfx:javafx-controls:${javaFxVersion}:${platform}"
        implementation "org.openjfx:javafx-fxml:${javaFxVersion}:${platform}"
        implementation "org.openjfx:javafx-graphics:${javaFxVersion}:${platform}"
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

shadowJar {
    archiveBaseName = "javafx-tutorial-duke"
    archiveClassifier = null
}
